# Generated by Django 4.1.3 on 2022-12-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courseProgress',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='submissions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='unitProgress',
            field=models.JSONField(default=dict),
        ),
    ]
