# Generated by Django 4.1.3 on 2022-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_graphs_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='responseType',
            field=models.CharField(choices=[('null', 'Null'), ('short answer', 'Shortanswer'), ('multiple choice', 'Multiplechoice')], default='null', max_length=20),
        ),
    ]
