# Generated by Django 4.1.3 on 2022-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_exercise_responsetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='responseType',
            field=models.CharField(choices=[('null', 'Null'), ('short_answer', 'Short_answer'), ('multiple_choice', 'Multiple_choice')], default='null', max_length=20),
        ),
    ]
