# Generated by Django 4.1.3 on 2022-12-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_exercise_responsetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='responseType',
            field=models.CharField(choices=[('N', 'null'), ('SA', 'short answer'), ('MC', 'multiple choice')], default='N', max_length=20),
        ),
    ]
