# Generated by Django 4.1.3 on 2022-12-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_exercise_responsetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='lessonId',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exampleId',
            field=models.ForeignKey(default='defaultId', on_delete=django.db.models.deletion.CASCADE, to='base.example'),
            preserve_default=False,
        ),
    ]
