# Generated by Django 4.1.3 on 2022-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_exercise_lessonid_exercise_exampleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pairs',
            field=models.JSONField(default=list),
        ),
    ]
