# Generated by Django 4.1.3 on 2022-12-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_lesson_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='choices',
            field=models.JSONField(default=list),
        ),
    ]
