# Generated by Django 4.1.3 on 2023-01-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_graph_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='renderingOrder',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
