# Generated by Django 4.1.3 on 2023-01-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_lesson_renderingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
