# Generated by Django 4.1.3 on 2023-01-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='imageFile',
        ),
    ]
