# Generated by Django 4.1.3 on 2023-01-20 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_file_image_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lessonId',
            field=models.ForeignKey(default='ALGqeafCTS', on_delete=django.db.models.deletion.CASCADE, to='base.lesson'),
            preserve_default=False,
        ),
    ]
