# Generated by Django 4.1.3 on 2023-01-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_image_lessonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageFile',
            new_name='file',
        ),
    ]
