# Generated by Django 4.1.3 on 2023-01-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='graph',
            name='expression',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='graph',
            name='mathBounds',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='graph',
            name='points',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='graph',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
